version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - data-streamer-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "data.events.v1"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    networks:
      - data-streamer-net

  data-streamer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka
    links:
      - kafka:kafka
    networks:
      - data-streamer-net

networks:
  data-streamer-net: